sudo: false
language: android
jdk: oraclejdk8

env:
  global:
    ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default) - to avoid ShellCommandUnresponsiveException on travis
android:
    components:
        - tools
        - platform-tools
        # The BuildTools version used by your project
        - build-tools-26.0.2

        # The SDK version used to compile your project
        - android-26
